### ISSUE TITLE
interpolation not working for Phoenix spectra

### ISSUE THREAD

**Issue by cmbergmann** [Stuermer/EchelleSimulator#16]
if you provide values that do not exist in the Phoenix library, it will crash and not interpolate (as suggested by 
./echellesiulator --help"
--> intermediate values will be rounded to available spectra"

eg. ./echellesimulator -s VeloceRosso -p 3800.,4.65,0.,0.,0. -t 1 -k 0 -r 0 -f 1 -o M5V.fit

will crash because there is a Phoenix spectrum for log g = 4.5 and one for 5.0 but none for 4.65

**Comment by Stuermer** [comment]
closing this since it is a 'problem' of the phoenix data rather than echelle++
