### ISSUE TITLE
Creating new spectrograph hdf unsuccessful

### ISSUE THREAD

**Issue by joedurbak** [Stuermer/EchelleSimulator#20]
[echellesimulator_output.txt](https://github.com/Stuermer/EchelleSimulator/files/5152029/echellesimulator_output.txt)
I'm a graduate student working on a grism based cross dispersed spectrometer ([RIMAS](https://aas235-aas.ipostersessions.com/Default.aspx?s=EB-39-A1-71-DF-90-D5-F7-67-F6-BB-29-2F-60-E2-E7)). Currently, I'm trying to simulate some RIMAS data via your stuermer/echellesimulator docker image. I've created an [HDF file](https://github.com/joedurbak/echelle_simulator_model_creation/blob/master/RIMAS_YJ.hdf) for RIMAS's Y and J bands optical arm, and managed to get the simulation to run (output attached), but it doesn't find photons within any of the orders. Would you mind taking a look at what I've done, or answering some questions about the hdf file requirements for the simulation? I've been working on this for a while now, and I'm stuck at this point.

Some notes on what I've tried so far:

- All of my code, the hdf file and the Zemax files can be found here: https://github.com/joedurbak/echelle_simulator_model_creation

- pyzdde doesn't seem to work very well with my version of Zemax so I did the following for the psfs and affine transformations:
    - I generated the Huygen PSFs in Zemax using the builtin functions, and created text files like [this one](https://github.com/joedurbak/echelle_simulator_model_creation/blob/master/PSF_YJ/no_use_centroid/config_3_wave_6.txt) and brought it into python using the get_psfs function on line 152 in this [python file](https://github.com/joedurbak/echelle_simulator_model_creation/blob/master/rimas.py)
    - I created a [macro ](https://github.com/joedurbak/echelle_simulator_model_creation/blob/master/macros/affine_dependencies.ZPL)for the affine transformation dependencies that output this [file](https://github.com/joedurbak/echelle_simulator_model_creation/blob/master/RIMAS_YJ_affine_dependencies.csv)
        - The output was parsed and affine transformations calculated using the do_affine_transformations function on line 170 within this [python file](https://github.com/joedurbak/echelle_simulator_model_creation/blob/master/rimas.py)
    - Even though my dispersion direction within the orders is actually along the y-axis, I deliberately swapped the axes when reading the data into python in case this was causing any issues with the simulation

**Comment by joedurbak** [comment]
Never mind... looks like something is wrong with my macro on further inspection

**Comment by Stuermer** [comment]
Since you provided me with the ZEMAX files, I can try to run the model creation with my ZEMAX. I can't promise when I have the time to do it. Maybe on the weekend !

**Comment by joedurbak** [comment]
> 
> 
> Since you provided me with the ZEMAX files, I can try to run the model creation with my ZEMAX. I can't promise when I have the time to do it. Maybe on the weekend !

Thank you! I solved the affine transformation issue I was having, but I still end up with zero photons per order. I'll let you know if I fix the problem before hand.

Quick question though, I chose the wavelength bounds for each order based on where the central envelope begins and ends rather than the bounds of the detector. Could this be causing my problem?

**Comment by Stuermer** [comment]
No, that should not be a problem.

**Comment by Stuermer** [comment]
I've been looking at the ZEMAX file. Is my assumption correct, that the bounding rectangle of the entrence slit is:
+/-0,0009720000   and +/- -0,0000833000 in angular units ?
Is it correct that the detector is 38x38mm and way bigger than the spectrum / the FSR ?

**Comment by joedurbak** [comment]
That is all correct

**Comment by joedurbak** [comment]
Sorry, I think my previous statement is a bit inaccurate. The spectrum could technically reach the edges of the detector without worrying about the FSR, but the intensity is quite small at that point. Which you can see in the echelle efficiencies here.   
<img width="896" alt="Screen Shot 2020-09-09 at 9 21 46 PM" src="https://user-images.githubusercontent.com/39345655/92670702-93894900-f2e2-11ea-8695-f9b480851a8b.png">

**Comment by Stuermer** [comment]
I was able to create the HDF file using the model_creation script with a few modifications to the ZEMAX file.
Does this look right ?
![image](https://user-images.githubusercontent.com/6728233/93067540-a5b90d80-f67b-11ea-9944-c9176c4ae861.png)
I did not have a value for the blaze. I put it to 30degres that gave me upper image. If that's not correct you can change that value in the .hdf file.
Please find the .hdf file here and let me know if that works for you or not!
https://stuermer.science/nextcloud/index.php/s/869M494kE4qNcyZ

**Comment by joedurbak** [comment]
That looks great! Thank you so much! Sorry I didn't respond sooner. The notification email from github was marked as "Promotions" for some reason. 

Would you mind telling me what you changed in the Zemax file to get it to work? I'd like to give it a go with the HK arm.

**Comment by joedurbak** [comment]
I just tried it out, and it looks great! Here is how it looks in comparison to the lab data we collected. 

Note: the lab data was taken with heavily degraded detectors where the only sensitive region is in the middle, and cuts the spectrum off at the edges of the orders

![image](https://user-images.githubusercontent.com/39345655/93421249-d321d900-f87e-11ea-8ee8-fe610f000314.png)

**Comment by joedurbak** [comment]
Just checking in again. Would you mind letting me see what you did to create the hdf file? Even just having the script, and zemax file would be incredibly helpful.

**Comment by Stuermer** [comment]
sorry for the late reply. Sure. Here's the zemax file and the script
https://stuermer.science/nextcloud/index.php/s/Fmr4d7HRdyCFg6s
Important steps (at least the ones I remember) for the ZEMAX file are: 
* remove all multi-configs
* make sure the field normalization is on 'rectangular'
* adjust PSF sampling to reasonable values (turns out the PSF is quite bad outside the FSR of the spectrograph, which is normal, since the optics have not been optimized for it. This leads to PSFs that can't even be calculated at the edges of the detector. A more reasonable thing to do would be to limit the wavelength range per order (right now, I trace everything till the edge of the detector
* for some reason I had to insert a fudge factor of 1.5 to get reasonable wavelengths to start with for the tracing. Does RIMAS have an immersion grating or so? (you can see the fudge factor here in the model creation script in line 14:  spectrograph.blaze = 43./1.5)

let me know if you need anything else

just FYI, I've been getting much closer finishing the python version of the simulator... this should be much easier then to use / maintain / contribute

**Comment by Stuermer** [comment]
closing this. seems solved. If not please reopen at [PyEchelle](https://gitlab.com/Stuermer/pyechelle).
